# -*- coding: utf-8 -*-
"""Calculadora Básica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18a26j4tx6JGXurBy4C6OdPjUhvCfCkl7
"""

# Criando uma calculadora básica
import time
import math

print("\033[31m***CALCULADORA***\033[0m")
print("Escolha a opção desejada:")
print("1.Soma\n2.Subtração\n3.Multiplicação\n4.Divisão\n5.Potência\n6.Raiz Quadrada\n7.Logaritmo Natural\n8.Sair")
opcao = int(input("\nDigite opção desejada: "))

while opcao < 1 or opcao > 8:
  opcao = int(input("Opção inexistente! Digite a correta!: "))

def calc_soma() -> float:
  soma = 0
  print('Digite os valores para o cálculo, para finalizar digite 0.')
  numero = float(input("Valor: "))
  while numero != 0:
    soma = soma + numero
    numero = float(input("Valor: "))
  print('A soma dos valores é: ', soma)

def sub(num1, num2: float) -> float:
  calc_sub = num1 - num2
  print('A subtração do valor 1 - valor 2 é:', calc_sub)
  # return calc_sub

def calc_mult() -> float:
  mult = 1
  print('Digite os valores para o cálculo, para finalizar digite 1.')
  numero = float(input("Valor: "))
  while numero != 1:
    mult = mult * numero
    numero = float(input("Valor: "))
  print('A muliplicação dos valores é: ', mult)

def div(num1, num2: float) -> float:
  calc_div = num1 / num2
  print('A divisão do valor 1 - valor 2 é:', calc_div)
  # return calc_div


if opcao == 1:        # Soma utilizando função
  soma_total = calc_soma()

elif opcao == 2:      # Subtração utilizando função
  num1 = float(input('Informe o 1º valor:'))
  num2 = float(input('Informe o 2º valor:'))
  result_sub = sub(num1,num2)

elif opcao == 3:      # Multiplicação utilizando função
  mult_total = calc_mult()

elif opcao == 4:      # Divisão utilizando função
  num1 = float(input('Informe o 1º valor:'))
  num2 = float(input('Informe o 2º valor:'))
  resul_div = div(num1,num2)

elif opcao == 5:
  poten = float(input('Informe o valor da potência:'))
  numero = float(input('Informe o valor que será elevado a potência indicada:'))
  print('O valor da potência é: ', pow(numero, poten))

elif opcao == 6:
  numero = float(input('Informe o valor para o cálculo de sua raiz quadrada:'))
  calc_raiz = math.sqrt(numero)
  print(f'A raiz quadra de {numero} é:{calc_raiz}')

elif opcao == 7:
  numero = float(input('Informe o valor para o cálculo de seu logaritmo natural:'))
  calc_log = math.log(numero)
  print(f"O logaritmo natural de {numero} é: {calc_log}")

elif opcao == 8:
  print('Calculadora encerrada....')
  time.sleep(2)
else:
    pass